name: Build and Run Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Установка нужной версии Clang
      - name: Install Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-14
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-14 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-14 100

      # Проверка версии компилятора
      - name: Check Clang Version
        run: clang --version

      # Install googletest
      - name: Install googletest
        uses: cvpkg/googletest-action@v0.1
        with:
          googletest_tag: 'release-1.11.0'

      # Run Clang-Tidy
      - name: Run Clang-Tidy
        run: |
          clang-tidy src/file1.cpp src/file2.tpp \
            -- -std=c++17 -I${{ github.workspace }}/include

      # Build project
      - name: Build Project
        run: make build

      # Run tests
      - name: Run Tests
        run: make test
